name: GiantRocketship-tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: automation
    env:
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: "Debug: Show world.ts"
        run: cat src/support/world.ts


      - name: Generate BDD test files
        run: npx bddgen

      - name: TypeScript compile check
        run: npx tsc --noEmit --skipLibCheck

      - name: Run tests with Allure
        run: npm run allure

      - name: Get Allure history
        if: always()
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: gh-pages
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
