name: GiantRocketship-tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
     image: mcr.microsoft.com/playwright:v1.41.0-jammy
    environment: automation
    env:
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Generate BDD test files
        run: npx bddgen

      - name: TypeScript compile check
        run: npx tsc --noEmit --skipLibCheck

      - name: Run tests with Allure
        run: npm run allure

      - name: Get Allure history
        if: always()
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_history: gh-pages
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
